### ISSUE TITLE
does not work 

### ISSUE THREAD

**Issue by kk433d** [dickreuter/cgt-share-matching-web#2]
the thing does not work, even with the template.

`No data to display`

**Comment by bndouglas** [comment]
I'm getting an error message when I try to upload the file. It tells me to provide a CSV with columns Date, Shares, Ticker. My CSV does have those columns. Also the template file you provided doesn't match the example on the home page, so it's hard to know what format of file the script is expecting.

**Comment by dickreuter** [comment]
Let me look into this. Will get back to you.
________________________________

**Comment by dickreuter** [comment]
the template does work. you need to select year 22/23
